const now = Date.now();

// Real Bhopal coordinates, verified against the actual 2024 ward polygons and
// real BMC zone/officer/corporator data in public/gis/bhopal (see
// scripts/convert-bhopal-gis.mjs) — not invented ward numbers or boundaries.
const bhopalWards = {
  ravindraNathTagore: {
    number: "34",
    name: "Ravindra Nath Tagore",
    lgdCode: 32961,
    zoneNumber: 8,
    corporator: "श्रीमती मीना यशवंत यादव",
    corporatorMobile: "9406903134",
    wardOfficer: "श्री हरिकेश यादव",
    wardOfficerMobile: "",
    population: 22798,
  },
  goswamiTulsidas: {
    number: "27",
    name: "Goswami Tulsidas Ward",
    lgdCode: null,
    zoneNumber: 6,
    corporator: "श्री प्रदीप मोनू सक्सेना",
    corporatorMobile: "",
    wardOfficer: "श्री गगन सोनी",
    wardOfficerMobile: "",
    population: null,
  },
  gulmohar: {
    number: "50",
    name: "Gulmohar Ward",
    lgdCode: null,
    zoneNumber: 9,
    corporator: "श्री बाबूलाल यादव",
    corporatorMobile: "",
    wardOfficer: "श्री प्रेम कुमार साक्य",
    wardOfficerMobile: "",
    population: null,
  },
};

export const sampleComplaints = [
  {
    complaintId: "cmp-bhopal-pothole-tagore",
    userId: "demo-user",
    regionId: "bhopal",
    latitude: 23.2459132753156,
    longitude: 77.40971718468094,
    accuracy: 22,
    city: "Bhopal",
    state: "Madhya Pradesh",
    country: "India",
    municipality: "Bhopal Municipal Corporation",
    ward: bhopalWards.ravindraNathTagore,
    zone: { number: 8, officerName: "Mr. Anil Sharma", officerMobile: "9424499908" },
    zoneName: "Zone 8",
    locality: "Ravindra Nath Tagore Ward market road",
    road: "Ward internal road",
    formattedAddress: "Ravindra Nath Tagore Ward, Zone 8, Bhopal, Madhya Pradesh",
    imageData: "",
    imageMimeType: "",
    imageSize: 0,
    imageHash: "",
    description: "Large pothole on the internal ward road is causing two-wheelers to swerve into oncoming traffic.",
    aiCategory: "Road Damage",
    aiSubcategory: "Pothole",
    aiPriority: "High",
    aiSummary: "A pothole on a ward internal road is creating a vehicle safety hazard.",
    aiSeverityScore: 7,
    aiCivicImpactScore: 70,
    aiRisks: { publicHealth: "Low", safety: "Medium", environmental: "Low", traffic: "Medium" },
    aiRecommendedAction: "Dispatch a Public Works Department crew to patch the pothole.",
    aiSuggestedDepartment: "Public Works Department",
    confidence: 0.88,
    tags: ["road", "pothole", "traffic"],
    status: "In Progress",
    supportCount: 18,
    duplicateGroupId: "grp-tagore-road",
    duplicatePercentage: 0,
    isDuplicate: false,
    clusterId: "",
    createdAt: new Date(now - 1000 * 60 * 60 * 18).toISOString(),
    updatedAt: new Date(now - 1000 * 60 * 35).toISOString(),
    slaDueAt: new Date(now + 1000 * 60 * 60 * 54).toISOString(),
    adminNotes: "Public Works Department crew assigned for patching.",
    assignedDepartment: "Public Works Department",
    assignedOfficer: "",
    resolutionImageData: "",
    resolvedAt: "",
    anonymous: false,
    timeline: [
      { label: "Reported", at: new Date(now - 1000 * 60 * 60 * 18).toISOString() },
      { label: "Assigned", at: new Date(now - 1000 * 60 * 60 * 8).toISOString() },
      { label: "In Progress", at: new Date(now - 1000 * 60 * 35).toISOString() },
    ],
  },
  {
    complaintId: "cmp-bhopal-garbage-tulsidas",
    userId: "demo-admin",
    regionId: "bhopal",
    latitude: 23.216082638724252,
    longitude: 77.3908310571482,
    accuracy: 30,
    city: "Bhopal",
    state: "Madhya Pradesh",
    country: "India",
    municipality: "Bhopal Municipal Corporation",
    ward: bhopalWards.goswamiTulsidas,
    zone: { number: 6, officerName: "Mr. Babu Lal Shikhri", officerMobile: "9424499906" },
    zoneName: "Zone 6",
    locality: "Goswami Tulsidas Ward residential lane",
    road: "Residential lane",
    formattedAddress: "Goswami Tulsidas Ward, Zone 6, Bhopal, Madhya Pradesh",
    imageData: "",
    imageMimeType: "",
    imageSize: 0,
    imageHash: "",
    description: "Garbage has not been collected from the street corner bin in over a week and is overflowing.",
    aiCategory: "Garbage",
    aiSubcategory: "Overflowing bin",
    aiPriority: "Medium",
    aiSummary: "An overflowing garbage bin needs collection to prevent a sanitation hazard.",
    aiSeverityScore: 5,
    aiCivicImpactScore: 45,
    aiRisks: { publicHealth: "Medium", safety: "Low", environmental: "Low", traffic: "Low" },
    aiRecommendedAction: "Schedule a Solid Waste Management collection run for this lane.",
    aiSuggestedDepartment: "Solid Waste Management Department",
    confidence: 0.91,
    tags: ["garbage", "sanitation"],
    status: "Open",
    supportCount: 31,
    duplicateGroupId: "grp-tulsidas-garbage",
    duplicatePercentage: 0,
    isDuplicate: false,
    clusterId: "",
    createdAt: new Date(now - 1000 * 60 * 60 * 7).toISOString(),
    updatedAt: new Date(now - 1000 * 60 * 60 * 7).toISOString(),
    slaDueAt: new Date(now + 1000 * 60 * 60 * 161).toISOString(),
    adminNotes: "",
    assignedDepartment: "Solid Waste Management Department",
    assignedOfficer: "",
    resolutionImageData: "",
    resolvedAt: "",
    anonymous: false,
    timeline: [{ label: "Reported", at: new Date(now - 1000 * 60 * 60 * 7).toISOString() }],
  },
  {
    complaintId: "cmp-bhopal-streetlight-gulmohar",
    userId: "demo-user",
    regionId: "bhopal",
    latitude: 23.1965366404948,
    longitude: 77.4415869805695,
    accuracy: 18,
    city: "Bhopal",
    state: "Madhya Pradesh",
    country: "India",
    municipality: "Bhopal Municipal Corporation",
    ward: bhopalWards.gulmohar,
    zone: { number: 9, officerName: "Mr. Nilesh Srivastava", officerMobile: "9424499909" },
    zoneName: "Zone 9",
    locality: "Gulmohar Ward park side",
    road: "Park boundary road",
    formattedAddress: "Gulmohar Ward, Zone 9, Bhopal, Madhya Pradesh",
    imageData: "",
    imageMimeType: "",
    imageSize: 0,
    imageHash: "",
    description: "Streetlight next to the park has been off for several nights, making the walkway unsafe after dark.",
    aiCategory: "Streetlight",
    aiSubcategory: "Non-functional light",
    aiPriority: "Medium",
    aiSummary: "A non-functional streetlight near the park is reducing night visibility and safety.",
    aiSeverityScore: 4,
    aiCivicImpactScore: 40,
    aiRisks: { publicHealth: "Low", safety: "Medium", environmental: "Low", traffic: "Low" },
    aiRecommendedAction: "Electricity Branch to inspect and replace the faulty streetlight fitting.",
    aiSuggestedDepartment: "Electricity Branch",
    confidence: 0.86,
    tags: ["streetlight", "safety"],
    status: "Resolved",
    supportCount: 9,
    duplicateGroupId: "grp-gulmohar-light",
    duplicatePercentage: 0,
    isDuplicate: false,
    clusterId: "",
    createdAt: new Date(now - 1000 * 60 * 60 * 72).toISOString(),
    updatedAt: new Date(now - 1000 * 60 * 60 * 10).toISOString(),
    slaDueAt: new Date(now - 1000 * 60 * 60 * 6).toISOString(),
    adminNotes: "Fitting replaced by Electricity Branch team.",
    assignedDepartment: "Electricity Branch",
    assignedOfficer: "",
    resolutionImageData: "",
    resolvedAt: new Date(now - 1000 * 60 * 60 * 10).toISOString(),
    anonymous: false,
    timeline: [
      { label: "Reported", at: new Date(now - 1000 * 60 * 60 * 72).toISOString() },
      { label: "Resolved", at: new Date(now - 1000 * 60 * 60 * 10).toISOString() },
    ],
  },
];

export const sampleVotes = [
  { voteId: "vote-1", complaintId: "cmp-bhopal-garbage-tulsidas", userId: "demo-user", createdAt: new Date(now - 1000 * 60 * 40).toISOString() },
  { voteId: "vote-2", complaintId: "cmp-bhopal-pothole-tagore", userId: "demo-user-2", createdAt: new Date(now - 1000 * 60 * 200).toISOString() },
];
